// Package wasmbridge carries the gowasm runtime and prepares it for emission
// into a generated package.
//
// The runtime lives in the runtime subdirectory as an ordinary Go package: it
// is compiled and unit-tested under GOOS=js GOARCH=wasm as part of this module,
// and the very same bytes are what generated code runs. Emitting it rather than
// having generated code import it means a project using gowasm needs no entry
// in its go.mod, and the runtime can never fall out of step with the generator
// that produced its caller, because both come from the same binary.
package wasmbridge

import (
	"embed"
	"fmt"
	"go/build/constraint"
	"go/parser"
	"go/token"
	"io/fs"
	"path"
	"sort"
	"strings"
)

// runtimeFS holds every file of the runtime package. Embedding the directory
// rather than naming files individually means a new runtime file is picked up
// without anything here having to change.
//
//go:embed runtime
var runtimeFS embed.FS

const runtimeDir = "runtime"

// File is one runtime file, ready to be written into the generated package.
type File struct {
	// Name is the file name to emit it under.
	Name string
	// Content is the rewritten source.
	Content []byte
}

// Source returns every runtime file rewritten to sit in the generated main
// package, sorted by name so output is stable.
func Source() ([]File, error) {
	entries, err := fs.ReadDir(runtimeFS, runtimeDir)
	if err != nil {
		return nil, fmt.Errorf("reading the embedded runtime: %w", err)
	}

	var out []File
	for _, entry := range entries {
		name := entry.Name()
		// Tests exercise the runtime here; they are not part of what ships.
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}

		src, err := fs.ReadFile(runtimeFS, path.Join(runtimeDir, name))
		if err != nil {
			return nil, fmt.Errorf("reading runtime file %s: %w", name, err)
		}
		content, err := rewriteToMain(name, src)
		if err != nil {
			return nil, fmt.Errorf("preparing runtime file %s: %w", name, err)
		}
		out = append(out, File{Name: emittedName(name), Content: content})
	}

	if len(out) == 0 {
		return nil, fmt.Errorf("the embedded runtime is empty")
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

// emittedName marks the file as generated in the package it lands in.
func emittedName(name string) string {
	return strings.TrimSuffix(name, ".go") + "_gen.go"
}

// rewriteToMain moves a runtime file into package main.
//
// The parser supplies the byte offsets, so nothing here searches the text for a
// package clause: a "package" that appears in a comment or a string cannot be
// mistaken for the real one. Everything after the package name is copied
// through untouched, which keeps the emitted body byte-identical to the source
// that was compiled and tested.
func rewriteToMain(filename string, src []byte) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, src, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		return nil, fmt.Errorf("parsing: %w", err)
	}
	if file.Name == nil {
		return nil, fmt.Errorf("no package clause")
	}

	offset := func(p token.Pos) int { return fset.Position(p).Offset }

	// The header runs to the package clause, or to its doc comment when it has
	// one, since that comment documents the original package and not this one.
	headEnd := offset(file.Package)
	if file.Doc != nil {
		headEnd = offset(file.Doc.Pos())
	}

	var b strings.Builder
	for _, line := range buildConstraints(string(src[:headEnd])) {
		b.WriteString(line)
		b.WriteString("\n")
	}
	if b.Len() > 0 {
		// A build constraint must be followed by a blank line to be recognised.
		b.WriteString("\n")
	}

	b.WriteString("// Code generated by gowasm from " + filename + ". DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// This is the gowasm runtime, emitted here rather than imported so that the\n")
	b.WriteString("// generated package depends on nothing outside your own module.\n\n")

	// No trailing newline: the remainder begins with whatever followed the
	// original package name.
	b.WriteString("package main")
	b.Write(src[offset(file.Name.End()):])

	return []byte(b.String()), nil
}

// buildConstraints returns the //go:build and // +build lines in a file header.
//
// Losing these would be silent and severe: without its constraint the runtime
// would be compiled for the host too, where syscall/js does not exist.
func buildConstraints(header string) []string {
	var out []string
	for _, line := range strings.Split(header, "\n") {
		trimmed := strings.TrimSpace(line)
		if constraint.IsGoBuild(trimmed) || constraint.IsPlusBuild(trimmed) {
			out = append(out, trimmed)
		}
	}
	return out
}
