package wasmbridge

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

// Every emitted file has to be valid Go in the generated main package, and has
// to keep its build constraint: without it a host build of the user's module
// would try to compile syscall/js.
func TestSourceEmitsValidMainPackage(t *testing.T) {
	files, err := Source()
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatal("no runtime files were emitted")
	}

	for _, f := range files {
		if !strings.HasSuffix(f.Name, "_gen.go") {
			t.Errorf("%s: emitted files should be marked as generated", f.Name)
		}

		text := string(f.Content)
		if !strings.HasPrefix(text, "//go:build js && wasm\n\n") {
			t.Errorf("%s: build constraint must come first and be followed by a blank line, got:\n%s",
				f.Name, firstLines(text, 3))
		}
		if !strings.Contains(text, "DO NOT EDIT") {
			t.Errorf("%s: generated output should say so", f.Name)
		}

		parsed, err := parser.ParseFile(token.NewFileSet(), f.Name, f.Content, parser.ParseComments)
		if err != nil {
			t.Errorf("%s: does not parse: %v", f.Name, err)
			continue
		}
		if parsed.Name.Name != "main" {
			t.Errorf("%s: package = %q, want main", f.Name, parsed.Name.Name)
		}
	}
}

// Generated registrations call these by name, unqualified.
func TestSourceProvidesTheGeneratedEntryPoints(t *testing.T) {
	files, err := Source()
	if err != nil {
		t.Fatal(err)
	}
	var all strings.Builder
	for _, f := range files {
		all.Write(f.Content)
	}
	for _, name := range []string{"Register", "Run", "Namespace"} {
		if !strings.Contains(all.String(), "func "+name+"(") {
			t.Errorf("emitted runtime is missing %s, which generated code calls", name)
		}
	}
}

// The emitted bytes must be the same code that is compiled and tested in this
// module, so those tests actually cover what users run.
func TestSourceBodyIsUnchanged(t *testing.T) {
	files, err := Source()
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		original := readRuntimeFile(t, strings.TrimSuffix(f.Name, "_gen.go")+".go")
		_, tail, found := strings.Cut(original, "\npackage runtime")
		if !found {
			t.Fatalf("%s: could not locate the original package clause", f.Name)
		}
		if !strings.HasSuffix(string(f.Content), tail) {
			t.Errorf("%s: the body was altered on the way out", f.Name)
		}
	}
}

// Test files stay in this module and are never shipped.
func TestSourceExcludesTests(t *testing.T) {
	files, err := Source()
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		if strings.Contains(f.Name, "_test") {
			t.Errorf("%s should not be emitted", f.Name)
		}
	}
	// The test file is embedded, so exclusion is a real decision, not an accident.
	if !strings.Contains(readRuntimeFile(t, "bridge_test.go"), "package runtime") {
		t.Error("expected the runtime's test file to be present in the embedded FS")
	}
}

// The rewrite takes its offsets from the parser, so text that merely looks like
// a package clause cannot be mistaken for one. A string-matching implementation
// gets every one of these wrong.
func TestRewriteUsesTheParserNotTextSearch(t *testing.T) {
	src := `//go:build js && wasm

// Package decoy documents this package.
//
// It mentions "package main" in prose, which must not be treated as a clause.
package decoy

const note = ` + "`package impostor`" + `

// Comment mentioning package elsewhere.
func Keep() string { return note }
`

	got, err := rewriteToMain("decoy.go", []byte(src))
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)

	parsed, err := parser.ParseFile(token.NewFileSet(), "decoy.go", got, parser.ParseComments)
	if err != nil {
		t.Fatalf("rewritten source does not parse: %v", err)
	}
	if parsed.Name.Name != "main" {
		t.Errorf("package = %q, want main", parsed.Name.Name)
	}

	// The decoys survive untouched: they were never the package clause.
	if !strings.Contains(text, "`package impostor`") {
		t.Error("a string literal containing 'package' was damaged")
	}
	if !strings.Contains(text, "Comment mentioning package elsewhere.") {
		t.Error("a comment containing 'package' was damaged")
	}
	if !strings.Contains(text, "func Keep() string") {
		t.Error("the declaration was lost")
	}
	// The original package's doc comment belongs to that package, not this one.
	if strings.Contains(text, "Package decoy documents") {
		t.Error("the original package doc should not be carried over")
	}
	if !strings.HasPrefix(text, "//go:build js && wasm\n") {
		t.Error("the build constraint was dropped")
	}
}

// A file with no build constraint should not gain a stray leading blank line.
func TestRewriteWithoutBuildConstraint(t *testing.T) {
	got, err := rewriteToMain("plain.go", []byte("package plain\n\nfunc A() {}\n"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(got), "// Code generated by gowasm") {
		t.Errorf("unexpected header:\n%s", firstLines(string(got), 3))
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "plain.go", got, 0); err != nil {
		t.Fatalf("does not parse: %v", err)
	}
}

func TestRewriteRejectsNonGo(t *testing.T) {
	if _, err := rewriteToMain("bad.go", []byte("this is not Go")); err == nil {
		t.Error("expected a parse error rather than silently emitting rubbish")
	}
}

func readRuntimeFile(t *testing.T, name string) string {
	t.Helper()
	b, err := runtimeFS.ReadFile("runtime/" + name)
	if err != nil {
		t.Fatalf("reading embedded %s: %v", name, err)
	}
	return string(b)
}

func firstLines(s string, n int) string {
	lines := strings.SplitN(s, "\n", n+1)
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, "\n")
}
