// Package config loads and validates gowasm.yaml.
package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"

	"github.com/paulgrammer/gowasm/internal/tsmap"
)

// FileName is the config file every command reads.
const FileName = "gowasm.yaml"

// NPM holds the fields copied verbatim into the generated package.json.
type NPM struct {
	Name        string `yaml:"name"`
	Version     string `yaml:"version"`
	Description string `yaml:"description,omitempty"`
	License     string `yaml:"license,omitempty"`
	Author      string `yaml:"author,omitempty"`
	Repository  string `yaml:"repository,omitempty"`
}

// Config is the whole of gowasm.yaml.
type Config struct {
	Package string   `yaml:"package"`
	Out     string   `yaml:"out"`
	NPM     NPM      `yaml:"npm"`
	Targets []string `yaml:"targets"`
	Int64   string   `yaml:"int64,omitempty"`

	// Dir is the directory holding the config; every relative path resolves
	// against it, so commands work from any subdirectory.
	Dir string `yaml:"-"`
}

// Find walks up from start looking for gowasm.yaml.
func Find(start string) (string, error) {
	dir, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		candidate := filepath.Join(dir, FileName)
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no %s found in %s or any parent directory; run 'gowasm init' first", FileName, start)
		}
		dir = parent
	}
}

// Load reads and validates the config nearest to start.
func Load(start string) (*Config, error) {
	path, err := Find(start)
	if err != nil {
		return nil, err
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var c Config
	if err := yaml.Unmarshal(raw, &c); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	c.Dir = filepath.Dir(path)
	c.applyDefaults()
	if err := c.Validate(); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &c, nil
}

func (c *Config) applyDefaults() {
	if c.Package == "" {
		c.Package = "."
	}
	if c.Out == "" {
		c.Out = "./node"
	}
	if c.NPM.Version == "" {
		c.NPM.Version = "0.1.0"
	}
	if len(c.Targets) == 0 {
		c.Targets = []string{"node", "browser"}
	}
	if c.Int64 == "" {
		c.Int64 = string(tsmap.Int64Number)
	}
}

// Validate reports the first problem that would make generation fail.
func (c *Config) Validate() error {
	if c.NPM.Name == "" {
		return fmt.Errorf("npm.name is required")
	}
	if err := ValidateNPMName(c.NPM.Name); err != nil {
		return fmt.Errorf("npm.name: %w", err)
	}
	for _, t := range c.Targets {
		if t != "node" && t != "browser" {
			return fmt.Errorf("targets: unknown target %q, want node or browser", t)
		}
	}
	switch tsmap.Int64Mode(c.Int64) {
	case tsmap.Int64Number, tsmap.Int64String:
	default:
		return fmt.Errorf("int64: want %q or %q, got %q", tsmap.Int64Number, tsmap.Int64String, c.Int64)
	}
	return nil
}

// Int64Mode is the validated int64 setting.
func (c *Config) Int64Mode() tsmap.Int64Mode { return tsmap.Int64Mode(c.Int64) }

// OutDir is the absolute path of the generated npm package.
func (c *Config) OutDir() string { return c.abs(c.Out) }

// BridgeDir is the path the generated Go main package appears at during a
// build. It is virtual: the directory is never created, and the file is
// supplied to the go command through an overlay. It sits outside the scanned
// package so that package always type-checks, generated or not.
func (c *Config) BridgeDir() string { return c.abs(".gowasm/wasmmain") }

func (c *Config) abs(p string) string {
	if filepath.IsAbs(p) {
		return p
	}
	return filepath.Join(c.Dir, p)
}

// Namespace is the prefix for the globals each instance installs itself under,
// derived from the unscoped npm name so two gowasm packages cannot collide.
func (c *Config) Namespace() string {
	name := c.NPM.Name
	if i := strings.LastIndex(name, "/"); i >= 0 {
		name = name[i+1:]
	}
	var b strings.Builder
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	out := b.String()
	if out == "" || unicode.IsDigit(rune(out[0])) {
		out = "pkg" + out
	}
	return out
}

// Write saves the config, creating parent directories as needed.
func (c *Config) Write(dir string) (string, error) {
	out, err := yaml.Marshal(c)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, FileName)
	header := "# Generated by 'gowasm init'. Edit freely, then run 'gowasm build'.\n"
	if err := os.WriteFile(path, append([]byte(header), out...), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// ValidateNPMName applies npm's own package-name rules.
func ValidateNPMName(name string) error {
	if name == "" {
		return fmt.Errorf("must not be empty")
	}
	if len(name) > 214 {
		return fmt.Errorf("must be 214 characters or fewer")
	}
	if strings.ToLower(name) != name {
		return fmt.Errorf("must be lowercase")
	}
	if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
		return fmt.Errorf("must not start with . or _")
	}

	body := name
	if strings.HasPrefix(name, "@") {
		scope, rest, ok := strings.Cut(name[1:], "/")
		if !ok || scope == "" || rest == "" {
			return fmt.Errorf("scoped names look like @scope/name")
		}
		if err := validNameChars(scope); err != nil {
			return fmt.Errorf("scope: %w", err)
		}
		body = rest
	}
	return validNameChars(body)
}

func validNameChars(s string) error {
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
		case r == '-' || r == '_' || r == '.' || r == '~':
		default:
			return fmt.Errorf("invalid character %q; use letters, digits, and - _ . ~", r)
		}
	}
	return nil
}
